# Generated by Django 4.2.1 on 2023-05-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('todo', '0002_tguser_alter_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='account.tguser'),
        ),
        migrations.DeleteModel(
            name='TgUser',
        ),
    ]
